### ISSUE TITLE
Pod Install fails

### ISSUE THREAD

**Issue by davidahouse** [Leanplum/Leanplum-tvOS-SDK-Example#1]
Installing Leanplum using PACKAGED/DYNAMIC
Cloning spec repo `leanplum` from `https://github.com/Leanplum/CocoaPods.git`
Analyzing dependencies
[!] Unable to find a specification for `Leanplum-tvOS-SDK (= 2.0.2)`

**Comment by milos1290** [comment]
@davidahouse The tvOS SDK should be released with next iOS version. It's currently in QA. So Example project can't find framework yet.

**Comment by GiarcEnoredlac** [comment]
@davidahouse should be able to update version to 2.0.5 with a minimum deploy target of 9.0 and pod install should run
